baseURL = "https://pasir.bangunan.co/"
languageCode = "id"
title = "Pasir Bangunan | Jual Pasir Bangunan Terdekat Gratis Ongkir dan Bongkar"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Supplier Pasir Berkualitas - Jual Pasir Bangunan dengan harga bersaing dan pengiriman gratis ongkir dan bongkar."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual pasir bangunan", "pasir murah", "supplier pasir", "pasir beton", "pasir urug", "pasir halus", "pasir pasang", "harga pasir bangunan"]
  base_price = 500000
  price_range = 100000
  free_shipping = true
  materials = [
  "Pasir Beton",
  "Pasir Urug",
  "Pasir Pasang",
  "Pasir Halus",
  "Pasir Sungai"
  ]
  categories = ["Pasir Bangunan", "Material Konstruksi", "Supplier Pasir"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Bandung", "Serang", "Purwakarta"]
  return_policies = [
  "Barang bisa dikembalikan dalam 1 hari jika tidak sesuai pesanan.",
  "Penggantian pasir tanpa biaya tambahan jika kualitas tidak sesuai.",
  "Pengembalian gratis untuk pasir yang tidak sesuai spesifikasi."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Agen Pasir Bangunan Terpercaya"
  hero_description = "Kami menawarkan berbagai jenis pasir berkualitas untuk kebutuhan konstruksi bangunan. Solusi ideal untuk material bangunan yang lengkap, dengan layanan gratis ongkir dan bongkar."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Pasir"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan pasir berkualitas tinggi dengan harga bersaing dan layanan pengiriman gratis ongkir dan bongkar. Juga, konsultasi gratis untuk membantu Anda memilih pasir yang tepat untuk proyek konstruksi Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "pasir.bangunan.co menawarkan berbagai jenis pasir berkualitas untuk kebutuhan konstruksi. Kami mengutamakan kepuasan pelanggan dengan produk yang berkualitas dan harga yang bersaing. Pilih kami untuk memenuhi kebutuhan pasir proyek bangunan Anda."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Fajar|Hendra|Agus|Samsul|Rio|Yudi}"
  message = "{Saya membeli pasir dari pasir.bangunan.co untuk proyek {rumah|bangunan|renovasi} saya, dan hasilnya {sangat memuaskan|luar biasa|menakjubkan}. Kualitas pasir {sangat baik|berkualitas tinggi|premium} dan pengirimannya {tepat waktu|cepat|sesuai jadwal}.|Pasir dari pasir.bangunan.co {berkualitas|kokoh|premium} dan pengirimannya {cepat|tepat|efisien} sesuai harapan.}"
  response = "{Terima kasih atas {kepercayaan|pilihan} Anda! Kami {senang|gembira} dapat menyediakan pasir berkualitas untuk proyek Anda.|Kami {menghargai|berterima kasih atas} kepercayaan Anda. Terima kasih sudah memilih pasir kami.}"
  rating = 4.6

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Maya|Ayu|Sari|Fitri|Lina|Diah|Nur}"
  message = "{pasir.bangunan.co {sangat membantu|mempermudah|memberikan solusi} dalam memilih jenis pasir untuk rumah saya. Produk yang saya {beli|pilih} {berkualitas|premium|bermutu} dan sesuai dengan {kebutuhan|keperluan} saya.|Saya {sangat terbantu|sangat puas} dengan pilihan pasir dari pasir.bangunan.co. Kualitasnya {baik|tinggi|premium} dan tepat untuk kebutuhan saya.}"
  response = "{Kami sangat {menghargai|berterima kasih atas} ulasan Anda. {Senang mendengar|Bahagia mengetahui} bahwa Anda puas dengan pasir dari kami.|Terima kasih banyak atas kepercayaan Anda, kami sangat senang mendengarnya.}"
  rating = 4.8

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Toni|Bayu|Gilang|Bambang|Faisal|Rizal|Ali|Ahmad|Rudi}"
  message = "{Pasir dari pasir.bangunan.co {sangat berkualitas|berkualitas tinggi|premium} dan cocok untuk proyek {perumahan|konstruksi|bangunan} saya. Proses pembelian dan pengirimannya juga {cepat|efisien|teratur}.|Saya {puas|terkesan|senang} dengan pasir dari pasir.bangunan.co. Pengirimannya {cepat|aman|terjamin} dan pasirnya {berkualitas|premium}.}"
  response = "{Terima kasih! Kami {berkomitmen|berdedikasi|fokus} untuk menyediakan pasir berkualitas dengan {layanan terbaik|pelayanan prima}.|Kami {senang|gembira} mendengar bahwa Anda puas dengan produk dan layanan kami.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Yanto|Toni|Faisal|Ari|Yoga|Agus|Gani|Dedi|Fajar}"
  message = "{Saya {sangat puas|senang|terkesan} dengan pasir dari pasir.bangunan.co. Kualitasnya {sangat baik|terbaik|tahan lama} dan {kokoh|kuat|awet} untuk proyek {konstruksi|bangunan|perumahan} saya.|Pasir dari pasir.bangunan.co {memuaskan|berkualitas tinggi|terbaik} dan sesuai dengan {kebutuhan|ekspektasi|standar} proyek saya.}"
  response = "{Senang mendengar Anda puas dengan produk kami. Terima kasih atas {kepercayaannya|pilihan Anda}!|Kami sangat {menghargai|berterima kasih atas} kepercayaan Anda. Terima kasih telah memilih produk kami.}"
  rating = 4.8

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Dewi|Lina|Ayu|Fitri|Sari|Diah|Nur|Maya}"
  message = "{Pelayanan pasir.bangunan.co {sangat memuaskan|luar biasa|terbaik}. Produk pasir yang saya {beli|pilih} {sangat berkualitas|bermutu tinggi|kokoh} dan sesuai dengan {harapan|ekspektasi|kebutuhan} saya.|Saya {sangat puas|senang|terkesan} dengan pelayanan dari pasir.bangunan.co. Pasir yang saya {gunakan|beli} {berkualitas|bermutu tinggi|premium} dan {ideal|sesuai} dengan harapan saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani|memenuhi kebutuhan} proyek Anda dengan pasir terbaik.|Kami sangat menghargai ulasan Anda. Terima kasih telah memilih produk kami!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Rio|Benny|Yudi|Galih|Iwan|Toni|Wawan|Rizky|Gani}"
  message = "{Pasir dari pasir.bangunan.co {sangat sesuai|tepat|cocok} dengan kebutuhan proyek renovasi rumah saya. Proses pengirimannya {cepat|terjamin|aman} dan {baik|teratur|efisien}.|Saya {senang|puas|terkesan} dengan pasir dari pasir.bangunan.co. Produk ini {sesuai|ideal} dan pengirimannya {cepat|aman|efisien}.}"
  response = "{Kami {senang|gembira|bahagia} mendengar bahwa Anda puas dengan produk kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah {memilih|mempercayai} produk kami. Kami {gembira|senang} Anda puas dengan hasilnya.}"
  rating = 4

[[params.tabelItems]]
  name = "Pasir Beton"
  price = "320.000 /m3"
[[params.tabelItems]]
  name = "Pasir Urug"
  price = "250.000 /m3"
[[params.tabelItems]]
  name = "Pasir Pasang"
  price = "280.000 /m3"
[[params.tabelItems]]
  name = "Pasir Halus"
  price = "550.000 /m3"
[[params.tabelItems]]
  name = "Pasir Hitam"
  price = "350.000 /m3"

[params.appliList]
  "Pasir Beton" = "digunakan untuk konstruksi beton, pondasi"
  "Pasir Urug" = "digunakan untuk pengurugan lantai"
  "Pasir Pasang" = "digunakan untuk pasang pondasi dan pemasangan bata"
  "Pasir Halus" = "digunakan untuk plester dinding, finishing"
  "Pasir Hitam" = "digunakan untuk campuran adukan beton"

[params.kegunaanList]
  "Pasir Beton" = "digunakan untuk membuat campuran cor yang kuat dan tahan lama"
  "Pasir Urug" = "cocok untuk meratakan dan mengurug lantai atau parkiran"
  "Pasir Pasang" = "digunakan untuk pemasangan bata atau batu pondasi"
  "Pasir Halus" = "cocok untuk plesteran, finishing halus dan pasang keramik atau marmer"
  "Pasir Hitam" = "digunakan dalam pembuatan adukan beton yang kuat"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Agen Pasir Bangunan Terlengkap | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"